interface Drive { path:string;label:string;configured:boolean;damaged:boolean;problem?:string;role?:"primary"|"recovery"|"legacy";provisionedRole?:"primary"|"recovery";generationId?:string }
interface ChainRequest { rpc:string;chainId:number;vaultAddress:string }
interface WithdrawalReview {reviewId:string;expiresAt:number;action:string;chainId:number;vaultAddress:string;beneficiary:string;amount:string;gasLimit:string;maxFeePerGas:string;estimatedFee:string;operationalNonce:string;deadline:string}
interface VorkaApi {
  listDrives():Promise<Drive[]>;generatePassword():Promise<string>;
  backupDevice(request:{sourcePath:string}):Promise<{canceled:boolean;role?:string;destination?:string;generationId?:string}>;
  restoreDevice(request:{destinationPath:string}):Promise<{canceled:boolean;role?:string;generationId?:string}>;
  generate(request:{primaryPath:string;recoveryPath:string;authPassword:string;fallbackPassword:string}):Promise<{authAddress:string;fallbackAddress:string;generationId:string}>;
  sponsorStatus():Promise<{available:boolean}>;
  createSponsoredVault(request:{primaryPath:string;beneficiary:string;activationCode:string}):Promise<{vaultAddress:string;factoryAddress:string;rpc:string;chainId:number;txHash:string}>;
  vaultOverview(request:ChainRequest):Promise<Record<string,string|boolean>>;
  createVault(request:{rpc:string;chainId:number;primaryPath:string;factoryAddress:string;beneficiary:string;password:string}):Promise<{vaultAddress:string}>;
  reviewWithdrawNative(request:ChainRequest&{primaryPath:string;amount:string;password:string}):Promise<WithdrawalReview>;
  confirmWithdrawNative(request:{reviewId:string;primaryPath:string;password:string}):Promise<{txHash:string}>;
  freezeVault(request:ChainRequest&{recoveryPath:string;recoveryPassword:string}):Promise<{txHash?:string;alreadyFrozen:boolean}>;
  replacePrimary(request:ChainRequest&{recoveryPath:string;replacementPath:string;recoveryPassword:string;newPrimaryPassword:string}):Promise<{txHash:string;newAuthAddress:string}>;
}
declare global{interface Window{vorka:VorkaApi}}
const el=<T extends HTMLElement>(id:string):T=>{const x=document.getElementById(id);if(!x)throw new Error(`Missing UI element: ${id}`);return x as T};
const val=(id:string)=>el<HTMLInputElement|HTMLSelectElement>(id).value.trim();
const errorBox=el("error"),infoBox=el("info");let drives:Drive[]=[],booting=true;
let pendingWithdrawalReview:WithdrawalReview|undefined;
function message(box:HTMLElement,text:string){box.textContent=text;box.classList.remove("hidden")}
function clearMessages(){errorBox.classList.add("hidden");infoBox.classList.add("hidden")}
function friendly(error:unknown):string{const raw=error instanceof Error?error.message:String(error);const text=raw.replace(/^Error invoking remote method '[^']+': Error:\s*/,"");if(/network|fetch|ECONN|SERVER_ERROR/i.test(text))return `RPC connection failed. Check the URL, network and chain ID. (${text})`;if(/password|decrypt/i.test(text))return `Password rejected. Check that the correct Vorka device is selected. (${text})`;if(/writable|EPERM|EACCES|read-only/i.test(text))return `The USB cannot be written. Check write protection and reconnect it. (${text})`;return text}
function fail(error:unknown){message(errorBox,friendly(error))}
function options(select:HTMLSelectElement,items:Drive[],placeholder:string){const previous=select.value;select.replaceChildren();const empty=document.createElement("option");empty.value="";empty.textContent=placeholder;select.append(empty,...items.map(d=>{const o=document.createElement("option");o.value=d.path;o.textContent=`${d.label} — ${d.path}`;return o}));if(items.some(d=>d.path===previous))select.value=previous}
type OnboardingMode="setup"|"recovery"|"bootstrap"|"mode"|"core";
interface PendingSetup{primaryPath:string;recoveryPath:string;authAddress:string;fallbackAddress:string;generationId:string}
const pendingKey="vorka-pending-onboarding";
let pendingSetup:PendingSetup|undefined;
try{pendingSetup=JSON.parse(localStorage.getItem(pendingKey)??"null")??undefined}catch{localStorage.removeItem(pendingKey)}
function showMode(mode:OnboardingMode){for(const [id,target] of [["setupPanel","setup"],["setupHero","setup"],["recoverySafetyPanel","recovery"],["vaultBootstrapPanel","bootstrap"],["modePanel","mode"],["corePanel","core"]])el(id).classList.toggle("hidden",mode!==target)}
function setCoreMode(mode:"local"|"online"){localStorage.setItem("vorka-core-mode",mode);el("coreModeStep").textContent=mode==="local"?"LOCAL RPC MODE":"VORKA ONLINE MODE";el("coreModeTitle").textContent=mode==="local"?"Connect to your Vault":"Your Vault, with Vorka connectivity";el("coreModeBadge").textContent=mode==="local"?"LOCAL SIGNING":"ONLINE + LOCAL SIGNING";showMode("core")}
function keyStatus(id:"primaryDetected"|"recoveryDetected",detected:boolean){const node=el(id),role=id==="primaryDetected"?"Primary":"Recovery";node.replaceChildren(document.createElement("span"),document.createTextNode(`${role} key ${detected?"detected":"undetected"}`));node.classList.toggle("detected",detected);node.classList.toggle("undetected",!detected)}
async function refresh(silent=false){if(!silent)clearMessages();try{drives=await window.vorka.listDrives();const fresh=drives.filter(d=>!d.configured&&!d.damaged),freshPrimaries=fresh.filter(d=>d.provisionedRole==="primary"),freshRecoveries=fresh.filter(d=>d.provisionedRole==="recovery"),configuredPrimary=drives.filter(d=>d.configured&&(d.role==="primary"||d.role==="legacy")),configuredRecovery=drives.filter(d=>d.configured&&d.role==="recovery"),configured=[...configuredPrimary,...configuredRecovery];if(freshPrimaries.length>1||freshRecoveries.length>1)throw new Error("Ambiguous USB roles: connect exactly one fresh PRIMARY key and one fresh RECOVERY key.");const primary=freshPrimaries[0],recovery=freshRecoveries[0];el<HTMLInputElement>("primaryDrive").value=primary?.path??"";el<HTMLInputElement>("recoveryDrive").value=recovery?.path??"";keyStatus("primaryDetected",Boolean(primary));keyStatus("recoveryDetected",Boolean(recovery));options(el("replacementDrive"),[...freshPrimaries,...configuredPrimary],"Select fresh primary or prepared replacement USB");options(el("coreDrive"),configuredPrimary,"Select configured primary key");options(el("recoveryCoreDrive"),configuredRecovery,"Select recovery key");options(el("backupSourceDrive"),configured,"Select configured Primary or Recovery key");options(el("restoreDestinationDrive"),fresh,"Select fresh provisioned destination key");const damaged=drives.find(d=>d.damaged);if(damaged)fail(`${damaged.problem??"Damaged Vorka bundle"} — ${damaged.path}`);if(pendingSetup){const primaryMatch=configuredPrimary.find(d=>d.path===pendingSetup!.primaryPath||d.generationId===pendingSetup!.generationId);const recoveryConnected=configuredRecovery.some(d=>d.path===pendingSetup!.recoveryPath||d.generationId===pendingSetup!.generationId);if(recoveryConnected)showMode("recovery");else if(primaryMatch){pendingSetup.primaryPath=primaryMatch.path;localStorage.setItem(pendingKey,JSON.stringify(pendingSetup));showMode("bootstrap");const status=await window.vorka.sponsorStatus();el("sponsorUnavailable").classList.toggle("hidden",status.available);el<HTMLButtonElement>("createSponsoredVault").disabled=!status.available}else{showMode("recovery");el("recoveryRemovalStatus").textContent="Recovery removed. Reconnect the Primary key to continue."}}else{showMode(configured.length?"core":"setup");if(!configured.length&&(!primary||!recovery))message(infoBox,"Connect one USB provisioned as PRIMARY and one provisioned as RECOVERY.")} }catch(e){fail(e)}finally{booting=false;el("loadingScreen").classList.add("loaded")}}
document.querySelectorAll<HTMLButtonElement>("[data-generate]").forEach(button=>button.addEventListener("click",async()=>{try{const id=button.dataset.generate!;const password=await window.vorka.generatePassword();el<HTMLInputElement>(id).type="text";el<HTMLInputElement>(`${id}2`).type="text";el<HTMLInputElement>(id).value=password;el<HTMLInputElement>(`${id}2`).value=password;message(infoBox,"A strong random password was generated. Store it separately before continuing.")}catch(e){fail(e)}}));
el<HTMLInputElement>("separateRecovery").addEventListener("change",event=>el("recoveryPasswordSetup").classList.toggle("hidden",!(event.target as HTMLInputElement).checked));
el<HTMLButtonElement>("createKeys").addEventListener("click",async()=>{clearMessages();const primaryPath=val("primaryDrive"),recoveryPath=val("recoveryDrive"),auth=val("auth"),auth2=val("auth2"),separate=el<HTMLInputElement>("separateRecovery").checked,fallback=separate?val("fallback"):auth,fallback2=separate?val("fallback2"):auth2;if(!primaryPath||!recoveryPath)return fail("Connect one PRIMARY and one RECOVERY Vorka key.");if(primaryPath===recoveryPath)return fail("Primary and recovery must be two different USB devices.");if(auth!==auth2)return fail("Passwords do not match.");if(fallback!==fallback2)return fail("Recovery passwords do not match.");const button=el<HTMLButtonElement>("createKeys");button.disabled=true;button.textContent="CREATING ENCRYPTED KEYS…";try{const r=await window.vorka.generate({primaryPath,recoveryPath,authPassword:auth,fallbackPassword:fallback});pendingSetup={primaryPath,recoveryPath,...r};localStorage.setItem(pendingKey,JSON.stringify(pendingSetup));for(const id of ["auth","auth2","fallback","fallback2"])el<HTMLInputElement>(id).value="";await refresh(true)}catch(e){fail(e)}finally{button.disabled=false;button.textContent="Create both encrypted keys"}});
el("createSponsoredVault").addEventListener("click",async()=>{clearMessages();try{if(!pendingSetup)throw new Error("The key setup context is missing");const r=await window.vorka.createSponsoredVault({primaryPath:pendingSetup.primaryPath,beneficiary:val("bootstrapBeneficiary"),activationCode:val("activationCode")});for(const [id,value] of Object.entries({rpc:r.rpc,chainId:r.chainId,vaultAddress:r.vaultAddress,factoryAddress:r.factoryAddress}))el<HTMLInputElement>(id).value=String(value);saveSettings();el<HTMLInputElement>("activationCode").value="";el("createdVaultSummary").textContent=`Vault ${r.vaultAddress} created and verified on chain.`;pendingSetup=undefined;localStorage.removeItem(pendingKey);showMode("mode")}catch(e){fail(e)}});
el("continueLocalBootstrap").addEventListener("click",()=>{if(pendingSetup)el<HTMLInputElement>("beneficiary").value=val("bootstrapBeneficiary");pendingSetup=undefined;localStorage.removeItem(pendingKey);setCoreMode("local");message(infoBox,"Enter your RPC and funded factory signer details to create the Vault locally.")});
el("chooseLocalMode").addEventListener("click",()=>setCoreMode("local"));
el("chooseOnlineMode").addEventListener("click",()=>setCoreMode("online"));
function chainRequest():ChainRequest{const chainId=Number(val("chainId"));if(!Number.isSafeInteger(chainId)||chainId<=0)throw new Error("Enter a valid positive chain ID.");return{rpc:val("rpc"),chainId,vaultAddress:val("vaultAddress")}}
function saveSettings(){localStorage.setItem("vorka-core-network",JSON.stringify({rpc:val("rpc"),chainId:val("chainId"),vaultAddress:val("vaultAddress"),factoryAddress:val("factoryAddress")}));message(infoBox,"Network settings saved locally on this computer.")}
function loadSettings(){try{const s=JSON.parse(localStorage.getItem("vorka-core-network")??"{}");for(const id of ["rpc","chainId","vaultAddress","factoryAddress"])if(s[id])el<HTMLInputElement>(id).value=String(s[id])}catch{localStorage.removeItem("vorka-core-network")}}
el("saveNetwork").addEventListener("click",()=>{clearMessages();saveSettings()});
el("loadVault").addEventListener("click",async()=>{clearMessages();try{const r=await window.vorka.vaultOverview(chainRequest());el("nativeBalance").textContent=String(r.nativeBalance);el("owner").textContent=String(r.owner);el("vaultAuth").textContent=String(r.authAddress);el("vaultFallback").textContent=String(r.fallbackAddress);el("frozen").textContent=r.frozen?"FROZEN":"ACTIVE";el("vaultCard").classList.remove("hidden");saveSettings()}catch(e){fail(e)}});
el("createVault").addEventListener("click",async()=>{clearMessages();try{const base=chainRequest();const primaryPath=val("coreDrive");if(!primaryPath)throw new Error("Select the configured primary Vorka key.");const r=await window.vorka.createVault({rpc:base.rpc,chainId:base.chainId,primaryPath,factoryAddress:val("factoryAddress"),beneficiary:val("beneficiary"),password:val("createVaultPassword")});el<HTMLInputElement>("vaultAddress").value=r.vaultAddress;el<HTMLInputElement>("createVaultPassword").value="";saveSettings();message(infoBox,`Vault created: ${r.vaultAddress}`)}catch(e){fail(e)}});
el("withdraw").addEventListener("click",async()=>{clearMessages();el("withdrawReview").classList.add("hidden");pendingWithdrawalReview=undefined;try{const base=chainRequest(),primaryPath=val("coreDrive");if(!primaryPath)throw new Error("Select the configured primary Vorka key.");const r=await window.vorka.reviewWithdrawNative({...base,primaryPath,amount:val("withdrawAmount"),password:val("withdrawPassword")});pendingWithdrawalReview=r;const fields:Record<string,string>={reviewAction:r.action,reviewChainId:String(r.chainId),reviewVault:r.vaultAddress,reviewBeneficiary:r.beneficiary,reviewAmount:`${r.amount} native`,reviewFee:`${r.estimatedFee} native (max fee per gas: ${r.maxFeePerGas} wei)`,reviewGas:r.gasLimit,reviewNonce:r.operationalNonce,reviewDeadline:new Date(Number(BigInt(r.deadline))*1000).toISOString()};for(const[id,text]of Object.entries(fields))el(id).textContent=text;el("withdrawReview").classList.remove("hidden")}catch(e){fail(e)}});
el("cancelWithdraw").addEventListener("click",()=>{pendingWithdrawalReview=undefined;el("withdrawReview").classList.add("hidden");el<HTMLInputElement>("withdrawPassword").value="";message(infoBox,"Withdrawal cancelled. Nothing was broadcast.")});
el("confirmWithdraw").addEventListener("click",async()=>{clearMessages();const review=pendingWithdrawalReview;pendingWithdrawalReview=undefined;el("withdrawReview").classList.add("hidden");try{if(!review||review.expiresAt<Date.now())throw new Error("Transaction review expired; review the withdrawal again");const primaryPath=val("coreDrive");if(!primaryPath)throw new Error("The reviewed Primary key is no longer selected");const r=await window.vorka.confirmWithdrawNative({reviewId:review.reviewId,primaryPath,password:val("withdrawPassword")});el<HTMLInputElement>("withdrawPassword").value="";message(infoBox,`Withdrawal confirmed: ${r.txHash}`)}catch(e){fail(e)}});
el("freezeVault").addEventListener("click",async()=>{clearMessages();try{const recoveryPath=val("recoveryCoreDrive");if(!recoveryPath)throw new Error("Select the dedicated recovery Vorka key.");if(!confirm("Freeze this Vault immediately? Daily operations will stop."))return;const r=await window.vorka.freezeVault({...chainRequest(),recoveryPath,recoveryPassword:val("recoveryPassword")});message(infoBox,r.alreadyFrozen?"Vault is already frozen.":`Vault frozen: ${r.txHash}`)}catch(e){fail(e)}});
el("replacePrimary").addEventListener("click",async()=>{clearMessages();try{const recoveryPath=val("recoveryCoreDrive"),replacementPath=val("replacementDrive"),password=val("newPrimaryPassword");if(!recoveryPath||!replacementPath)throw new Error("Select the recovery key and a fresh replacement USB.");if(password!==val("newPrimaryPassword2"))throw new Error("New primary passwords do not match.");if(!confirm("Freeze the Vault, create a replacement primary key, and rotate authorization?"))return;const r=await window.vorka.replacePrimary({...chainRequest(),recoveryPath,replacementPath,recoveryPassword:val("recoveryPassword"),newPrimaryPassword:password});message(infoBox,`Primary key replaced: ${r.newAuthAddress}. Transaction: ${r.txHash}`);await refresh()}catch(e){fail(e)}});
el("backupDevice").addEventListener("click",async()=>{clearMessages();try{const sourcePath=val("backupSourceDrive");if(!sourcePath)throw new Error("Select one configured Vorka device to back up.");const r=await window.vorka.backupDevice({sourcePath});if(r.canceled)return message(infoBox,"Backup cancelled. Nothing was copied.");message(infoBox,`${String(r.role).toUpperCase()} encrypted backup verified and saved to ${r.destination}. Store it separately from the other role.`)}catch(e){fail(e)}});
el("restoreDevice").addEventListener("click",async()=>{clearMessages();try{const destinationPath=val("restoreDestinationDrive");if(!destinationPath)throw new Error("Select a fresh provisioned Vorka device to restore onto.");if(!confirm("Restore the selected encrypted backup onto this fresh Vorka device? Existing key material is never overwritten."))return;const r=await window.vorka.restoreDevice({destinationPath});if(r.canceled)return message(infoBox,"Restore cancelled. Nothing was changed.");message(infoBox,`${String(r.role).toUpperCase()} backup restored and verified. Generation: ${r.generationId}`);await refresh()}catch(e){fail(e)}});
loadSettings();void refresh();window.setInterval(()=>void refresh(true),5000);export{};
